### ISSUE TITLE
Question: use cases

### ISSUE THREAD

**Issue by joeblew99** [pagarme/teleport#9]
This is very cool.

I am curious why this was written specifically. Maybe others too ?

When you have a cluster you can apply changes to one dB instance, and the changes propagate too all others.
But there must be a multitude of use cases this solves and probably a few you only discover after running a big postresql system. 
Hence,the use cases are valuable to know

**Comment by pedrofranceschi** [comment]
Hi Jow,

Thanks for the support!

So, we started writing this because we simply could not find a replicator
that did both DML and DDL replication in AWS RDS, where you don't have
access to WAL or (real) superuser permissions. Migrating out of RDS seemed
sort of a extreme measure to get a simple read-replica working, so Teleport
was born :-)

Many replicators support DML replication using triggers (Slony etc), but
all of them lack DDL support, specially in constrained environments - and
that was the premise we had in mind while building it.

During the development, the design got fairly solid and it became clear
that it could also be used in a multitude of replication scenarios. So far
we've been using Teleport to create two read-replicas (two targets on
source, so our data team can access real-time production data). But we are
also aware of people using Teleport just fine for master-master replication
as well.

What use cases are you trying to address? We can surely help you to achieve
the desired setup.

Best,

Pedro

**Comment by joeblew99** [comment]
Hey Pedro,


So useful !

I have not any specific use case right now, but this is really useful. I have a new project next week where I need to run postresql on ecd.

It would be very useful to add this "why ?" To the readme.

Also interestingly this repo would be used with convox. 
https://github.com/convox
Have a look and see what you think.
I am thinking of using teleport with convox.

It takes a while to find great tools like these.

**Comment by joeblew99** [comment]
And probably this :

https://github.com/mwitkow/go-flagz

**Comment by pedrofranceschi** [comment]
Yep, teleport should work just fine with convox and flagz. Let me know if you face any issues.

**Comment by joeblew99** [comment]
Will do. Thanks Pedro
